-- Supabase SQL skript na vytvorenie tabuľky documents
-- Tento skript treba spustiť v Supabase -> SQL Editor -> New Query

CREATE TABLE IF NOT EXISTS public.documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  date TEXT NOT NULL,
  status TEXT NOT NULL,
  size TEXT NOT NULL,
  supplier TEXT,
  customer TEXT,
  amount NUMERIC,
  category TEXT,
  "fileUrl" TEXT,
  "fileType" TEXT,
  "supplierIco" TEXT,
  "supplierDic" TEXT,
  "supplierIcDph" TEXT,
  "customerIco" TEXT,
  "customerDic" TEXT,
  "customerIcDph" TEXT,
  "dueDate" TEXT,
  "deliveryDate" TEXT,
  "fullData" JSONB DEFAULT '[]'::jsonb,
  "isPaid" BOOLEAN DEFAULT false,
  "isChecked" BOOLEAN DEFAULT false,
  
  -- Nové stĺpce pre priradenie k používateľovi a firme
  "userEmail" TEXT NOT NULL,
  "companyName" TEXT NOT NULL,
  
  -- Automatický dátum vytvorenia
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Pridanie RLS (Row Level Security) politík, aby používatelia videli len svoje dáta
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Povolit vsetko pre vsetkych"
ON public.documents
FOR ALL
USING (true)
WITH CHECK (true);
